# whitelist
branches:
  only:
    - master
    - dev
    - dev-staged
    - add_tests

os:
    - linux
    # - osx

language: python

matrix:
    include:
        - python: 3.8

before_install:
    - if  [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - bash install.sh test-environment
    - source activate test-environment

script:
    - pytest --co 
    - travis_wait 60 pytest -v --cov=windse

after_success:
  - coveralls