name: windse_temp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - mpich=4.1.2=hd33e60e_101
  # - mpich=4.0.3
  - coveralls
  - dolfin-adjoint=2019.1.0
  - fenics
  - hdf5
  - jsonschema
  - matplotlib
  - memory_profiler
  - openmdao
  - pandas
  - pyoptsparse
  - pytest
  - pytest-cov
  - pytest-mpi
  - pyyaml
  - scipy
  - slepc
  - sphinx<7.0.0
  - pip
  - pip:
    - git+https://github.com/blechta/tsfc.git@2018.1.0
    - git+https://github.com/blechta/COFFEE.git@2018.1.0
    - git+https://github.com/blechta/FInAT.git@2018.1.0
    # - git+https://github.com/firedrakeproject/tsfc.git@Firedrake_20220119.0
    # - git+https://github.com/coneoproject/COFFEE.git@Firedrake_20220119.0
    # - git+https://github.com/FInAT/FInAT.git@Firedrake_20220119.0
    - singledispatch
    - networkx
    - pulp
    - fatpack
    - gmsh
    - meshio
    - -e .
