name: windse_temp
channels:
  - conda-forge
  - defaults
dependencies:
  - coveralls
  - dolfin-adjoint=2019.1.0
  - fenics=2019.1.0=py39h6e9494a_26
  - hdf5
  - matplotlib
  - memory_profiler
  - mshr=2019.1.0
  - openmdao==3.16.0
  - pandas
  - pyoptsparse
  - pytest
  - pytest-cov
  - pytest-mpi
  - pyyaml
  - scipy=1.7.0
  - slepc
  - pip
  - pip:
    - git+https://github.com/blechta/tsfc.git@2018.1.0
    - git+https://github.com/blechta/COFFEE.git@2018.1.0
    - git+https://github.com/blechta/FInAT.git@2018.1.0
    # - git+https://github.com/firedrakeproject/tsfc.git@Firedrake_20220119.0
    # - git+https://github.com/coneoproject/COFFEE.git@Firedrake_20220119.0
    # - git+https://github.com/FInAT/FInAT.git@Firedrake_20220119.0
    - singledispatch
    - networkx
    - pulp
    - fatpack
    - -e .
