name: CI_every_PR_parallel

# We run CI on push commits on all branches
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: CI_every_PR_parallel
    runs-on: macos-latest
        
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        # https://github.com/marketplace/actions/setup-miniconda
        with:
          miniconda-version: "latest"
          channels: conda-forge
          auto-update-conda: true
          # python-version: 3.8
          # environment-file: environment.yml
      
      - name: Install test environment
        shell: pwsh # putting in a shell command makes for compile linking problems later
        # (if you use the shell here, cannot use 'compiler' package, but mpi only seems to work with it)
        run: |
          bash ./install.sh test-environment
          conda activate test-environment
          conda list
        
      # - name: Run parallel regression tests within WindSE
      #   shell: pwsh
      #   run: |
      #     conda activate test-environment
      #     pytest -sv --cov=windse tests/test_regression_parallel.py

      # - name: Run parallel regression tests within WindSE
      #   shell: pwsh
      #   run: |
      #     conda activate test-environment
      #     cd tests/9-Regression
      #     mpirun -n 2 windse run ALM_Unsteady.yaml -p general:name:ALM_Unsteady_np_2 

      - name: Run parallel regression tests within WindSE
        shell: pwsh
        run: |
          conda activate test-environment
          cd tests/9-Regression
          mpirun -n 2 python -u ../../windse_driver/driver.py run ALM_Unsteady.yaml -p general:name:ALM_Unsteady_np_2 
          # mpirun -n 2 python -u ../../windse_driver/driver.py run Floating_ALM.yaml -p general:name:Floating_ALM_np_2 
