name: CI_every_commit

# We run CI on push commits on all branches
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: CI_every_commit
    runs-on: macos-latest
        
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        # https://github.com/marketplace/actions/setup-miniconda
        with:
          miniconda-version: "latest"
          channels: conda-forge
          auto-update-conda: true
          python-version: 3.8
      #     environment-file: environment.yml
      
      # can be used to ssh into the github actions node
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      
      - name: Install test environment
        shell: pwsh # putting in a shell command makes for compile linking problems later
        # (if you use the shell here, cannot use 'compiler' package, but mpi only seems to work with it)
        run: |
          conda install -n base mamba
          bash ./install.sh test-environment
          conda activate test-environment
          conda list

      # Run all tests within WindSE, but not computationally expensive examples
      - name: Run tests within WindSE
        shell: pwsh
        run: |
          conda activate test-environment
          pytest -sv --cov=windse tests/test_regression.py
      
      # Run coveralls
      - name: Run coveralls
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          conda activate test-environment
          coveralls --service=github